    # nixpacks.toml - Force .NET 8 SDK

    [phases.setup]
    # Explicitly request ONLY the .NET 8 SDK package.
    # Removed "..." to avoid inheriting defaults that might include .NET 6.
    nixPkgs = ["dotnet-sdk_8"]

    [start]
    # Confirm this matches your API project's assembly name
    cmd = "./out/sssync-backend.api"